### ISSUE TITLE
 [Flags] enum : long does not deserialize

### ISSUE THREAD

**Issue by okinkela** [kevin-montrose/Jil#210] opened 2016-03-04 23:30 UTC
class Program
    {
        [Flags]
        public enum Works
        {
            A = 1,
            B = 2
        }
        [Flags]
        public enum Broken : long
        {
            A = 1,
            B = 2
        }

        static void Main(string[] args)
        {
            Works works = Jil.JSON.Deserialize<Works>(Jil.JSON.Serialize<Works>(Works.A));
            Broken broken = Jil.JSON.Deserialize<Broken>(Jil.JSON.Serialize<Broken>(Broken.A));
        }
    }

**Comment by Wazner** [comment] 2016-03-06 00:41
Is this a duplicate of #206 ?

**Comment by Soenneker** [comment] 2016-03-06 18:21
@Wazner Yes.

**Comment by kevin-montrose** [comment] 2016-03-10 18:41
Was fixed by #206

**Closed by kevin-montrose** 2016-03-10 18:41 UTC
