### ISSUE TITLE
Null exception when serialize List<BaseClass>

### ISSUE THREAD

**Issue by foxwendy** [kevin-montrose/Jil#292] opened 2018-02-08 21:06 UTC
public class MyBaseClass      
    {    
        [DataMember]
        string FileName{get;set;}
        [DataMember]
        string FileCreationTime{get;set;}
        public MyMaseCalss(string[] rawRecord)
        {
                this.FileName = rawRecord[0];
                this.FileCreationTime = rawRecord[1];
         }
     }

    public class MySubClass : MyBaseClass
    {
        [DataMember]
        float X;
        public MySubClass (string[] rawRecord):base(rawRecord)
        {
                this.X= rawRecord[2];
         }
    }

Then I get a list of MySubClass object as List<MyBaseClass>(I'd want to use MyBaseClass type in the list here because I have other sub classes.). When I try to serialize the list as in the following code, JSON.Serialize threw out an NullReference Exception at the base class's constructor function. I saw the rawRecord value is null there. So looks to me that the sub class's constructor was not called. I could guess wrong, but could you point me to a right direction?  Thanks!

        private string JilSerialize(List<MyBaseClass> jsonObjs)
        {
            using (var output = new StringWriter())
            {
                JSON.Serialize(
                   jsonObjs,
                    output,
                    Options.ISO8601IncludeInherited
                );
                return output.ToString();
            }
        }

**Comment by kevin-montrose** [comment] 2019-03-13 23:19
Your example doesn't compile, a `string` cannot be assigned to the `X` field.

However, when _building_ a (de)serializer Jil will try and probe types to get layout information.  I bet what you're seeing is an exception (which is later caught) during that probe.  The constructors are called in the correct order (subverting that is difficult, perhaps even impossible, in .NET), but with only default parameters.

I'm closing this issue as I cannot reproduce an exception being thrown out of the JSON.Serialize call site.

**Closed by kevin-montrose** 2019-03-13 23:19 UTC
