### ISSUE TITLE
OutOfRangeException and long.MinValue

### ISSUE THREAD

**Issue by MadRabbitKiller** [kevin-montrose/Jil#147] opened 2015-07-22 10:35 UTC
Serializing long.MinValue throws OutOfRangeException. 

```
// works
 var good = JSON.Serialize(new { Value = long.MinValue + 1 });

// fails
 var bad = JSON.Serialize(new { Value = long.MinValue });
```

**Comment by Wazner** [comment] 2015-07-22 15:20
I can reproduce this. 

I tracked down the source of the bug and it is caused by a typo in `ThunkWriter.cs`, line 71.
```C#
enum ConstantString_Min : ushort
{
    Int_MinValue = (0 << 8) | 11,
    Long_MinValue = (12 << 8) | 20
}
```
Should be:
```C#
enum ConstantString_Min : ushort
{
    Int_MinValue = (0 << 8) | 11,
    Long_MinValue = (11 << 8) | 20
}
```
Notice the `12` turning into a `11` for the `Long_MinValue` member.

I'll post a pull request regarding this issue including unit tests later today after I get home.
For now, if you need it a.s.a.p., apply the changes yourself; otherwise wait for the pull request to be merged.

**Comment by MadRabbitKiller** [comment] 2015-07-22 15:38
Thank you for detailed clarification

**Closed** 2015-07-23 18:59 UTC
