### ISSUE TITLE
Expected a double value 

### ISSUE THREAD

**Issue by ZOXEXIVO** [kevin-montrose/Jil#156] opened 2015-08-28 11:32 UTC
When I'm trying to deserialize simple JSON data - i catch "Expected a double value " in Value parameter. Why double data so strong, why it not possible to use int and convert it as default ?

{"Type":{"id":1,"name":"Ex"},"Value":"634654","Group":{"Id":"e6139fad-08c3-4085-856e-3c694f62b792","Members":null,"Name":null},"Currency":{"Id":1,"Display":"РУБ","Name":"USD"}}

**Comment by Wazner** [comment] 2015-08-28 17:41
It is actually possible to use an integer, but that's not the cause of your problem.

Jil is quite strict in what kinds of data it accepts to get optimal performance. The `Value` field in your JSON is a string and not a double because it is surrounded by quotes.

If you can change the code that generated the JSON you should change it to a number instead of a string.

If you cannot, then you will need to change the type of the `Value` field of your C# class to a string and do the parsing yourself.

**Comment by ZOXEXIVO** [comment] 2015-08-31 07:50
Thank you.

**Comment by Wazner** [comment] 2015-09-02 09:46
Could you close this issue if my comment has solved your problem. This helps us to keep track of open issues. Thank you.

**Closed** 2015-09-02 11:30 UTC
