### ISSUE TITLE
DateTime deserialization depends on system timezone

### ISSUE THREAD

**Issue by divan-9** [kevin-montrose/Jil#248] opened 2016-11-21 12:28 UTC
I've just realize that deserialization works differently with different system time zones. 

The test method below passes when system time zone is set to UTC (or any negative ones / I believe so, though haven't checked), but fails with +03 TZ.

Is it made by design? If so, do we have any workaround except changing system tz?
```csharp
        [TestMethod]
        public void ReproduceOutOfRangeException()
        {
            using (var str = new StringReader("\"0001\""))
            {
                DateTimeOffset dto = JSON.DeserializeDynamic(str, Options.ISO8601Utc);
                Assert.AreEqual((DateTimeOffset)new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Local), dto);
            }
        }
```

**Comment by Wazner** [comment] 2016-11-21 17:42
The DateTimeOffset returned by Jil will be in UTC timezone (because you're using the Utc option). The reason why your test is failing is because you're comparing an UTC `DateTimeOffset` to a local one.

Try any of the below examples:

Comparing UTC to UTC
```C#
Assert.AreEqual((DateTimeOffset)new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Utc), dto);
```

Comparing the equivalent (when in UTC+3) to UTC
```C#
Assert.AreEqual((DateTimeOffset)new DateTime(1, 1, 1, 3, 0, 0, DateTimeKind.Local), dto);
```

Comparing Local to Local
```C#
Assert.AreEqual((DateTimeOffset)new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Utc).ToLocal(), dto.ToLocal());
```

If you want to interpret the `DateTimeOffset` returned by Jil as local time, use the `DateTime.SpecifyKind` method.
```C#
var dto = JSON.DeserializeDynamic(str, Options.ISO8601Utc);
dto = (DateTimeOffset)dto.DateTime.SpecifyKind(DateTimeKind.Local);
Assert.AreEqual((DateTimeOffset)new DateTime(1, 1, 1, 0, 0, 0, DateTimeKind.Local), dto);
```

**Comment by MadRabbitKiller** [comment] 2016-11-21 19:31
I'm sorry for misleading you, the assert might be incorrect, but the real problem with OutOfRangeException. It's throws as result of converting local date 0001-01-01 to DateTimeOffset which leads to negative value.

**Comment by ArtemAstashkin** [comment] 2016-12-05 11:31
Hello! I've caught the same issue too.
try to run the following test, I think it is a bit clear:
`
        [Test]
        public void ReproduceOutOfRangeException()
        {
            using (var str = new StringReader("\"0001\""))
            {
                var dto = JSON.DeserializeDynamic(str, Options.ISO8601Utc);

                JSON.SerializeDynamic(dto, Options.ISO8601Utc);
            }
        }`

It fails with ArgumentOutOfRangeException on the line "JSON.SerializeDynamic(dto, Options.ISO8601ExcludeNullsIncludeInherited);"

**Closed** 2019-03-20 15:10 UTC
